# Generated by Django 4.0 on 2021-12-16 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('accounts', '0003_alter_advuser_current_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='all_questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='all_questions', to='questions.QuestionsModel'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='current_questions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questions.questionsmodel', verbose_name='Текущий вопрос'),
            preserve_default=False,
        ),
    ]
