# Generated by Django 4.0 on 2021-12-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('accounts', '0004_advuser_all_questions_advuser_current_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='all_questions',
            field=models.ManyToManyField(related_name='all_questions', to='questions.QuestionsModel'),
        ),
    ]
