# Generated by Django 4.0 on 2021-12-16 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('accounts', '0005_alter_advuser_all_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='current_questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.questionsmodel', verbose_name='Текущий вопрос'),
        ),
    ]
