# Generated by Django 4.0 on 2021-12-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_answermodel_question'),
        ('accounts', '0006_alter_advuser_current_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='current_questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.questionsmodel', verbose_name='Текущий вопрос'),
        ),
    ]
